### PR TITLE
Added the PHPClasses 2020 entry.

### PR DESCRIPTION
**Pull request by manuellemos**

### CODE REVIEW

**Comment by nfabre** [comment]
Why is this PR not yet merged, since elephants can be found at this address? 
https://www.phpclasses.org/shop/category/ms/

**Comment by jgrossi** [comment]
folks what's the different between this elephpant and the 2018 version? it's the same, same color, but a different "production" correct? for example: we have the blue elephpant, we have different elephpants (productions) but the model is the same

any comments please?

**Comment by doppynl** [comment]
Looks the same to me. Just a new production run.
If you were to add each production run, then the opengoodies blue&pink would have to be on it more than twice as well. Don't think we want that.

**Comment by nfabre** [comment]
I understand your point of view and I'm in line with it, but to be consistent we have to rename the elephpant "PHPClasses 2018" to PHPClasses.

**Comment by jgrossi** [comment]
thanks for the feedback folks. gonna rename the `PHPClasses 2018` to just `PHPClasses` if we have another color later of something we change the name and then create a new one. thanks all

**Comment by jgrossi** [comment]
changed the name and photo for the "phpclasses" one in here https://github.com/jgrossi/elephpant.me/pull/55/files

once that PR is merged I close this one

**Comment by IgorSantos17** [comment]
I agree with you, it is a new production of the same model, it seems to me that it has had some small improvements, but it remains the same.
The best strategy is to update the existing data and close this PR.

**Pull request closed without merging**
