### PR TITLE
Add Thelia Elephpant

### PR DESCRIPTION
**Pull request by lopes-vincent**
Hi all !  

Here is a new elephant with the effigy of Thelia an Opensource Ecommerce solution.

### CODE REVIEW

**Comment by jgrossi** [comment]
hey @lopes-vincent do you have any tweet or URL to link to this PR? thanks for sharing

**Comment by IgorSantos17** [comment]
heey @jgrossi here is the tweet in official profile: https://twitter.com/theliaecommerce/status/1470395791495868421
we can add this specimen to the site

**Review by IgorSantos17 — APPROVED** [review]

**Review by cookieguru — APPROVED** [review]
Officially for sale today https://twitter.com/theliaecommerce/status/1527251934905778177

**Comment by doppynl** [comment]
I think this can be merged and put live, as I just received mine. :-).

Maybe the year 2022 is more appropriate, as that is the year it landed. 2021 is probably when it was announced.

**Comment by teiling88** [comment]
My package arrived today. Can be merged I guess :-)

**Pull request merged**
