### PR TITLE
Added Notive elephpant

### PR DESCRIPTION
**Pull request by imbue**
@notivenl got a batch of elephpants produced and we are giving some away (https://twitter.com/assertliam/status/1654133370245328896). This merge requests adds them to the elephpant.me registry including a photo

### CODE REVIEW

**Comment by Fichtme** [comment]
Would like to see this pr merged!

**Review by jgrossi — APPROVED** [review]

**Comment by imbue** [comment]
Thanks for merging! Is there anything I can do to help with a deployment?

**Comment by jgrossi** [comment]
hey @imbue there's an issue happening preventing the deploy. investigating and let you know asap

**Comment by imbue** [comment]
Something I can do to help? I figured https://github.com/jgrossi/elephpant.me/pull/163 might have something to do with the issues, are there problems on the side of imgur with rate limits?

**Comment by jgrossi** [comment]
hey @imbue yep. it seems our IP was blocked by imgur that's returning 429s. I think now we have to change the json file to point each image to the image file locally instead.

if that's something you can help with it's really appreciated. otherwise, I might be able to fix that tomorrow evening

**Comment by imbue** [comment]
@jgrossi so basically the idea would be to just store the images in repo (i.e in /resources) and continue from there?

**Pull request merged**
