### PR TITLE
Add PHP Classes Pink

### PR DESCRIPTION
**Pull request by pgrimaud**
I just received the pink and licensed version from PHP Classes.

### CODE REVIEW

**Comment by IgorSantos17** [comment]
I think we should discuss adding phpclasses elephpants, they are really different and "ugly".
there are several variations.
what do you think @jgrossi and @pgrimaud ?

**Comment by cookieguru** [comment]
Perhaps track the manufacturer?

**Comment by cookieguru** [comment]
Also not sure how we're going to track all the varients of the PhpClasses elePHPant; they have a blanket license to produce different variations, so is this different than the light blue PhpClasses elePHPant?

**Comment by doppynl** [comment]
'model' could also be an option. There is another slightly different model for phpcon grandpa and phpce.

**Comment by IgorSantos17** [comment]
I think we could keep only the current one that is already on the site. because all the others are variations.
elephpant phpce is closer to the original than any phpclasses.

**Comment by pgrimaud** [comment]
PHP Classes only released Blue and Pink as Open Goodies. I think adding the PHP Classes is fine atm, but if they will release a new color, we should talk about a complete revamp ?

**Comment by teiling88** [comment]
There is a licensed version of an elephpant and you won't add him because you don't like him or the manufacturer?

**Comment by cookieguru** [comment]
> [@manuellemos](https://twitter.com/manuellemos/) has an excePHPtional authorization. (It's the only one). He can create an elephpant with his very personal design (we like it or we don't like it)...but... blues and pinks only and with sticker only. Others must go through me to create an official elephpant.

-- [Vincent Pontier](https://twitter.com/Elroubio/status/1534857887549358087)


The same license was [extended](https://twitter.com/manuellemos/status/1534832656671723520) to produce the Upinside elePHPants.

There are likely several variants, the [newest variant](https://twitter.com/manuellemos/status/1534772397638819840) of PHP Classes blue is a slightly lighter shade what's pictured [on the site](https://elephpant.me/storage/elephpants/41-phpclasses.jpg).  There is also [a PHP8 version from PHP Classes](https://twitter.com/manuellemos/status/1534773693175447552)

**Comment by cookieguru** [comment]
@pgrimaud Can you update the branch?

**Comment by teiling88** [comment]
I destroyed the branch from @pgrimaud so I created a new one https://github.com/jgrossi/elephpant.me/pull/183 🙈

**Comment by pgrimaud** [comment]
> I destroyed the branch from @pgrimaud so I created a new one #183 🙈

No worries, this PR was so old 😂

**Pull request closed without merging**
