### PR TITLE
Store all elePHPant images locally

### PR DESCRIPTION
**Pull request by cookieguru**
See https://github.com/jgrossi/elephpant.me/pull/162#issuecomment-1556275717

This commit:
* Removes all references to Imgur images
* Copies all the former Imgur links to this repo
* Formats elephpants.json to have consistent spacing

This lays the groundwork for allowing clickable images to show the full size version.  There would need to be a migration to update these paths; currently on the URL to the thumbnail is stored, see https://github.com/jgrossi/elephpant.me/blob/f4e920b0527aa54c710ae15eb842ac318d1db1d2/app/Console/Commands/ReadElephpants.php#L29

### CODE REVIEW

**Comment by imbue** [comment]
Thumbnail creation can be fixed by using the image from public path:

```diff
private function processImage(object $elephpant): ?string
{
    if (isset($elephpant->image) && $elephpant->image) {
+       $localImagePath = public_path(sprintf('/images/elephpants/%s',$elephpant->image));
+       $image = Image::make($localImagePath);
-       $image = Image::make($elephpant->image);
        $image->fit(300);
        $imageName = sprintf('%d-%s.jpg', $elephpant->id, Str::slug($elephpant->name));
        $image->save(storage_path(sprintf('app/public/elephpants/%s', $imageName)));

        return $imageName;
    }

}
```

**Comment by jgrossi** [comment]
PR looks good. thanks @cookieguru and @imbue for the changes.

@cookieguru can you update the `ReadElephpants.php`file with @imbue 's suggestion please?

then I test locally and deploy 🚀

**Comment by imbue** [comment]
Created a PR (https://github.com/cookieguru/elephpant.me/pull/1/files) to add the modifications to @cookieguru's PR

**Comment by cookieguru** [comment]
Thanks for the assist @imbue!

@jgrossi ready for review

**Comment by jgrossi** [comment]
thanks man! I’m AFK but will review later today 💪

**Review by jgrossi — APPROVED** [review]

**Pull request merged**
