### PR TITLE
Add PHPStan and Eddie Elephpants

### PR DESCRIPTION
**Pull request by JonPurvis**
This PR adds 2 new Elephpants to the website:

- PHPStan is getting an Elephpant. [Confirmed on Twitter](https://twitter.com/OndrejMirtes/status/1738828882306895912) by the creator of PHPStan.

- Eddie is being given out to those that purchase a ticket for PHP UK. [Also confirmed on Twitter](https://twitter.com/PHPUKConference/status/1748317638848074102)

I'll keep an eye out for some better photos, but I'd quite like to get these on the site soon!

### CODE REVIEW

**Comment by JonPurvis** [comment]
@teiling88 @jgrossi 

Does this look okay to you?

**Comment by jgrossi** [comment]
yep looks good to me

**Review by jgrossi — APPROVED** [review]

**Comment by JonPurvis** [comment]
You're welcome!

**Comment by JonPurvis** [comment]
@jgrossi Whilst you're here, would you be open to accepting https://github.com/jgrossi/elephpant.me/pull/174? 

The Sylius Elephpant reached its funding goal this morning so it reminded me the PR existed 😆

**Comment by teiling88** [comment]
Hey @JonPurvis,
I didn't find the time for testing this mr. I think in the next week it will be merged or commented :-)

**Comment by JonPurvis** [comment]
No problem @teiling88, PHPStan isn't realised yet and Eddie won't be given out until the conference happens in Mid February so it's not like anyone has them to add to their Herd yet, all good! 👍

**Comment by teiling88** [comment]
My comment was about #174  :-) 

This one is merged and will be deployed the next days :-)

**Comment by JonPurvis** [comment]
My bad 😆

**Comment by JonPurvis** [comment]
@teiling88 Hey, do you know when this PR is likely to be deployed? Lots of people now have Eddie (the conference finished today).

**Comment by jgrossi** [comment]
hey! just deployed! all good ;-)

**Comment by JonPurvis** [comment]
Awesome, thanks @jgrossi - I'm going to try and source a different picture of Eddie, one without the PHPUK logo in the top left of the picture!

**Pull request merged**
