### PR TITLE
Added large size elephpants

### PR DESCRIPTION
**Pull request by wimg**
I added the large (jumbo) size elephpants. They are in the db in a field "size" (free text, who knows what we get in the future).

Fixes https://github.com/jgrossi/elephpant.me/issues/7

### CODE REVIEW

**Comment by wimg** [comment]
Will squash first ;-)

**Comment by doppynl** [comment]
Might be better to show the size when it is not "normal" and give all existing elephpants a size of "normal" or "small". Implementation would be a bit cleaner.
Currently it shows the size when it is "large" and hides it in all other cases.

**Comment by pgrimaud** [comment]
Will you recreate a PR @wimg?

**Comment by wimg** [comment]
I will, but currently reinstalling my dev system after a hardware problem. Give me a few days.

**Comment by wimg** [comment]
@doppynl Re-reading your comment... isn't what you're saying contradictory ? Or am I misreading ?

**Comment by doppynl** [comment]
I think my comment wasn't very clear. I'll try to rephrase it.

The implementation in the pull request checks the size and if it is "large" it will display the size. In other cases it will not show the size.
What would happen if a new size was added? Like a "Tiny" for instance.

To me the implementation would be more clean if:

- All elephpants get a size configured. Existing ones would get "small" for instance. (although "normal" would also be a fine choice).
- When displaying size, only display it when it is not "small" and use the size property to display instead of hardcoded "large".

This would also make it easier to make additions in the future. Like new sizes, or filtering based on size.

**Comment by wimg** [comment]
Made a new pull request #86 to handle this.

**Pull request closed without merging**
