### PR TITLE
fix(trading): add missing parameter country

### PR DESCRIPTION
**Pull request by pgrimaud**
👋 Hello there!

Long time no see...

We have a fatal error on those 2 routes: 
- `/trade/senders/{elephpantId}`
- `/trade/receivers/{elephpantId}`

```bash
ErrorException
Undefined variable: country (View: /Users/pgrimaud/workspace/oss/elephpant.me/resources/views/trade/index.blade.php)
http://127.0.0.1:8000/trade/receivers/1
```

### CODE REVIEW

**Review by jgrossi — APPROVED** [review]

**Review by teiling88 — APPROVED** [review]

**Comment by teiling88** [comment]
and deployed - thank you for your contribution :-)

**Comment by pgrimaud** [comment]
Great! Have you issues about performance? I saw very high latency on some
pages. 😰

Pierre Grimaud
IT Consulting / Web Development / Software Engineering
+33 6 85 18 30 37
https://p.ier.re
https://github.com/pgrimaud

**Comment by teiling88** [comment]
Yes there are some performance impacts cause of the used Models there. Will fix it after my vacation :-) 

I saw your profile, are you interested in a trade? One Symfony 10 Years Elephpant for an PHPartner? :D

**Comment by pgrimaud** [comment]
@teiling88 I'm sorry bro. The Symfony 10 Years Elephpant, is so rare (500 specimens only). I keep it for a "special" trade. 😞

**Pull request merged**
