### PR TITLE
Added CMGT ElePHPant as number 73

### PR DESCRIPTION
**Pull request by antwanvdm**
Hi! I added our educational ElePHPant as number 72. All alumni get a new friend to remember their study forever. It's the ultimate PHP gesture from an educational perspective. I tried to get it on this website and 'afieldguidtoelephpants' by delivering information to contacts, but luckily @imbue pointed me at the option to create a pull request which seems to be faster. :)

Thanks in advance for approval and deployment!
(More information in Dutch can be found here: https://cmgt.hr.nl/elephpant)

### CODE REVIEW

**Comment by JonPurvis** [comment]
Keep an eye on https://github.com/jgrossi/elephpant.me/pull/169 because that'll add number 72 if merged and deployed first so this one should be 73

**Comment by JonPurvis** [comment]
Really cool Elephpant though!

**Comment by antwanvdm** [comment]
Ah thanks for the heads up @JonPurvis ! Should I change the number in the PR, or will they get published together, and will it be fixed during deployment?

**Comment by JonPurvis** [comment]
No problem @antwanvdm! 

You'll need to change it in this PR because if they're both merged as they currently are, we'll end up with 2 number 72's in the seeder class, which will most likely then cause an error on deployment because the IDs will conflict.

Don't forget to change the image name too, less important, but keeps it consistent 😄 

P.S is there _any_ other way of acquiring this elephpant? I really want one 😆

**Comment by antwanvdm** [comment]
> No problem @antwanvdm!
> 
> You'll need to change it in this PR because if they're both merged as they currently are, we'll end up with 2 number 72's in the seeder class, which will most likely then cause an error on deployment because the IDs will conflict.
> 
> Don't forget to change the image name too, less important, but keeps it consistent 😄
> 
> P.S is there _any_ other way of acquiring this elephpant? I really want one 😆

Yes, it's done! Thanks again.

The ElePHPant itself has been requested by multiple people on my Twitter timeline as well. Unfortunately, I have to give you the same answer 🙈. Currently, it is only available for our graduating students. If it gets available in the future in a different way, I'll be sure to communicate via my Twitter timeline or via the CMGT_hr instagram channel.

**Comment by JonPurvis** [comment]
Understood 😄 

Thanks for sorting the IDs out!

**Comment by teiling88** [comment]
Pls rebase your branch than we can merge it :-)

**Comment by JonPurvis** [comment]
@teiling88 I'd be happy to re-create this PR, if needed, so it's included in the next deployment (and so it also allows Elephpant 74 to be deployed too!)

**Comment by cookieguru** [comment]
Those with write access should already be able to rebase it https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/

**Comment by antwanvdm** [comment]
I'm currently on holiday, so feel free to help @JonPurvis. Also a little confused on what would need to happen now, since I don't understand why there even is a merge conflict. Probably best to continue so that 72, 73 and 74 can be released together 🎉

**Comment by cookieguru** [comment]
rebase != merge conflict

In this case it just means updating your branch so all the recent addions to master are included

**Review by teiling88 — APPROVED** [review]

**Comment by teiling88** [comment]
A rebase would fix the merge conflict @cookieguru 
The merge conflict is resulted that everybody wants to add an entry at the bottom of the elephpants.json. 

So I had the rights to do it local. Will be merged soon.

**Comment by antwanvdm** [comment]
Super. Thanks! Can't wait for the release!

**Comment by teiling88** [comment]
At the moment only @jgrossi can make a release/deployment.

**Comment by JonPurvis** [comment]
Thanks for getting them all merged for us @teiling88, much appreciated 😄

**Comment by jgrossi** [comment]
deployed 🎉

**Comment by antwanvdm** [comment]
Super, thanks @jgrossi !

**Pull request merged**
