### PR TITLE
Add Vonage elePHPant

### PR DESCRIPTION
**Pull request by cookieguru**
https://github.com/philipsharp/afieldguidetoelephpants/pull/151

https://twitter.com/SecondeJ/status/1580670531841687552

### CODE REVIEW

**Comment by derickr** [comment]
Please merge this, I have one too :-)

**Comment by jgrossi** [comment]
hey can we have an image, please? ❤️ 🐘

**Review by cookieguru — COMMENTED** [review]
@derickr Do you have a photo?  I can't find one that allows for re-use under this project's license

**Comment by derickr** [comment]
Not yet. But I can make one.

**Comment by derickr** [comment]
PHP
http://derickrethans.nl/files/dump/d51_3720_processed.jpg

Vonage
http://derickrethans.nl/files/dump/d51_3721_processed.jpg

**Comment by derickr** [comment]
Hi — can this be merged please? I have two now :-)

**Review by jgrossi — APPROVED** [review]

**Pull request merged**
