### PR TITLE
#122 - adding mollie elephpant

### PR DESCRIPTION
**Pull request by teiling88**

### CODE REVIEW

**Comment by IgorSantos17** [comment]
hey @jgrossi here is the tweet: https://twitter.com/Fabian_ikono/status/1448966334025506837
we can add this specimen to the site

**Review by IgorSantos17 — APPROVED** [review]

**Comment by boxblinkracer** [comment]
i need that one being merged too...already waiting to add it :D

**Comment by jgrossi** [comment]
is there just one or did they already produced at scale?

**Comment by teiling88** [comment]
They produced theme at scale. But the didn't startet to give them away. Based on the tweet mentioned above I had the chance to get one over our Mollie contact person. :)

**Comment by boxblinkracer** [comment]
there are indeed more people who already have it :D 
me, and i've seen a couple on twitter too,
but i think the give-away was indeed limited at the moment

**Comment by teiling88** [comment]
| but i think the give-away was indeed limited at the moment
You have to be good connected with Mollie I guess :)

**Review by jgrossi — APPROVED** [review]

**Pull request merged**
