### PR TITLE
filter trade area by country

### PR DESCRIPTION
**Pull request by JonPurvis**
A lot of the time when browsing the trade area, I'm interested in seeing Elephpants for trade in the UK, currently the only way to do that is go through each page and carefully look for users that are marked as being in the UK.

This PR adds the ability to filter the trade area by country, so a user can easily filter trades by their country or a specific country. I've also added a handy button to select your own country, instead of finding it in the dropdown. 

image

I've also amended the pagination so that it keeps the country in the URL when you switch pages.

### CODE REVIEW

**Comment by cookieguru** [comment]
Just looking at the screenshot, it's not clear that clicking "My Country" is going to change the value of the dropdown: a) the verbiage isn't a call to action and b) it's using the success color and not the color of something that would make the UI perform an action

What if instead the user's country was always the first one in the list?

Alternatively, is there a use case for filtering on a country other than the user's own?

**Comment by JonPurvis** [comment]
Great points @cookieguru 

I've swapped the button to use the `secondary` CSS class, which I think makes sense given the other button is `primary`. I've also altered the text so it's clear what clicking it will do:

image

I think a good use case for filtering by a specific country, instead of just your own is if you're planning on attending a conference/event outside of your country and you want to try and arrange some trades ahead of time. You could narrow it by country and then check to see if any of the remaining traders will also be at the conference/event. For me, I'd currently have to go through 15 pages worth of trades whereas if I was attending a conference in the UK, I'd perhaps narrow it down to show UK only traders which is only 1 or 2 pages.

**Comment by teiling88** [comment]
@JonPurvis can you please rebase this branch? So we can merge it after the final test? :-)

**Comment by JonPurvis** [comment]
@teiling88 done! Feel free to give it a test 😄

**Comment by teiling88** [comment]
@JonPurvis sorry - can you please rebase your branch one last time please? :-)

**Comment by JonPurvis** [comment]
@teiling88 this one should be good now too! 😄

**Comment by teiling88** [comment]
Will test it local the next days and merge it afterwards :-)

**Comment by JonPurvis** [comment]
Excellent, thank you!

Would you be able to give the following 2 PRs a test too? 😄 

- https://github.com/jgrossi/elephpant.me/pull/175
- https://github.com/jgrossi/elephpant.me/pull/174

Thanks!

**Pull request merged**
