### PR TITLE
add yomeva elephpant (#72)

### LINKED ISSUE #168: Yomeva ElePHPant is missing
The new Yomeva ElePHPant is missing

FzymO2wX0AIYVI6

### PR DESCRIPTION
**Pull request by JonPurvis**
Fixes #168

### CODE REVIEW

**Review by teiling88 — APPROVED** [review]

**Comment by teiling88** [comment]
Thanks for your contribution :-)

**Comment by JonPurvis** [comment]
@jgrossi Please could you merge this? I don't have permission. Mine has actually arrived now 😄

**Comment by chrisemerson** [comment]
Excellent work, came here to see if I could add it myself but I can see it's already done :)

**Comment by JonPurvis** [comment]
Hey @jgrossi @IgorDuarte17 👋 

Would you guys be open to having an extra maintainer for this project?

**Comment by teiling88** [comment]
Hey @JonPurvis, 
as far as I know is @jgrossi the only one who can deploy the new versions. So a new maintainer is at the moment not need unless @jgrossi give us more rights. We (playox.de) offered some sponsoring and the logic for some kind of auto deploymet but @jgrossi seems to be very busy.

**Comment by JonPurvis** [comment]
Understood! Having it deploy via Laravel Envoyer would be a good option, although it is a paid product, but you can have multiple team members.

Thanks for merging this one though! 👍

**Comment by jgrossi** [comment]
deployed 🎉

**Comment by JonPurvis** [comment]
Thanks very much @jgrossi 🔥

**Pull request merged**
